markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

exclude:
    scripts

highlighter: rouge
permalink: date
name: Jared Parsons
url: http://blog.paranoidcoding.com
description: Rantings of a Programmer
gravatar_url: https://www.gravatar.com/avatar/704c8748a47dc407815d79591af8482e

author:
    name: jaredpar
    email: jared@paranoidcoding.org
    github: jaredpar
    twitter: jaredpar
    bio: The ramblings and rantings of <a href="https://twitter.com/jaredpar">@jaredpar</a>
    stackoverflowid: 23283
    email_md5: 704c8748a47dc407815d79591af8482e

title: Paranoid Coding

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

rss_path: atom.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

BASE_PATH:
