markdown: redcarpet
pygments: true
permalink: date
rdiscount:
  extensions: [smart]

name: Jared Parsons
url: http://twitter.com/jaredpar
description: Rantings of a Programmer
twitter: jaredpar
github: jaredpar
gravatar_url: http://www.gravatar.com/avatar/529ba429a58902bef56c2fcb672d5ccb
