markdown: redcarpet
highlighter: pygments
permalink: date
name: Jared Parsons
url: http://blog.paranoidcoding.com
description: Rantings of a Programmer
gravatar_url: http://www.gravatar.com/avatar/529ba429a58902bef56c2fcb672d5ccb

author:
    name: jaredpar
    email: jaredpparsons@gmail.com
    github: jaredpar
    twitter: jaredpar
    email_md5: 529ba429a58902bef56c2fcb672d5ccb

title: Paranoid Coding

paginate: 5
paginate_path: "page:num"

rss_path: atom.xml
categories_path: categories.html
tags_path: tags.html

redcarpet:
    extensions: [footnotes]

BASE_PATH:
